### PR TITLE
fix(73-75): order and styling in latest tx graph

### LINKED ISSUE #73: [QA] In the transaction history graph filtered by 1M, the date format is not correct.
**Environment:**
MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.
https://front.staging.wormscan.io/#/

**Steps**
1. Go to https://front.staging.wormscan.io/#/
2. Click on the 1M button on the transaction history graph
3. Observe the dates on the x-axis

**Obtained result:** 
The date is ordered in descending order and is not in an easy-to-read format.

**Expected result:**
The date should be following the design on Figma, please click the link to see: https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormScan?type=design&node-id=2190-22152&t=wW1BqhLzFU1mVOUu-0

**Evidence:**
Screenshot 2023-05-19 at 3 15 12 PM

### PR DESCRIPTION
**Pull request by raop155**
# Description

Fixes #73 #75

- Fix order in the `Latest tx graph`
- Fix labels format

image

### CODE REVIEW

File: src/components/molecules/TransactionHistoryChart/index.tsx [hunk 1]
```diff
@@ -60,18 +64,27 @@ const TransactionHistoryChart = ({ range }: Props) => {
...
                   name: "LastTxsData",
                   data: seriesData,
                 },
               ]}
               options={{
+                title: {
+                  text: totalTxs,
+                  align: "left",
+                  style: {
+                    color: "#6a6da0",
```
Comment (yuli-ferna) [inline src/components/molecules/TransactionHistoryChart/index.tsx:82]: Can you use a color palette here?

**Review by yuli-ferna — APPROVED** [review]

File: src/components/molecules/TransactionHistoryChart/index.tsx (hunk 1 above)
Comment (raop155) [reply src/components/molecules/TransactionHistoryChart/index.tsx:82]: Tested, and it support it 🤚 
I will do the changes!

Comment (raop155) [reply src/components/molecules/TransactionHistoryChart/index.tsx]: done
