### PR TITLE
Fix/72 73 multple fixes

### LINKED ISSUE #72: [QA] Top assets volume(USD) should show without decimals
**Environment:** 

- MacBook Pro, macOS Ventura 13.1.1, Chrome Version 113.0.5672.63.
- https://front.staging.wormscan.io/#/

Steps

1. Go to https://front.staging.wormscan.io/#/
2. Go to Top 7 assets 
3. Observe the volume in USD

**Obtained result:** 
Values ​​are shown with two decimal places.

**Expected result:**
Regarding the design https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormScan?type=design&node-id=998-22574&t=5QdQbe8hEljHnZfj-0
the values(USD) should not have decimals. 

**Evidence**
Screenshot 2023-05-16 at 10 02 37 PM

### PR DESCRIPTION
**Pull request by raop155**
# Description

Fixes #72, #74 

### Performance

- Change `svg` background to `wepb` background // This was the root cause of the poor performance.

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -4,6 +4,7 @@ import "./index.scss";
 import "./styles/globals.scss";
 import "./i18n";
 import App from "./App";
+window.devicePixelRatio = 1; // To handle poor performance on high resolution screens
```
Comment (valentinoConti) [inline src/index.tsx:7]: This is wrong right here, look at this PR: https://github.com/XLabs/wormscan-ui/pull/56

We are using the real devicePixelRatio to generate better resolution graphics for devices that have bigger resolutions than their viewport like Macs or high-end mobile devices. If we force it to be 1 the pixelated graphic bug will reappear.

There are some Android devices that have a devicePixelRatio of 3 while they have 4GB RAM or low-end CPUs/GPUs, that's mostly a device bad design than it is an error on our side. If we want to implement a fix for those devices we have to do a device-specific solution using some benchmark mechanism or at least a user-agent mechanism, to force the pixelRatio only on med/low-end android devices

**Review by valentinoConti — APPROVED** [review]

**Review by yuli-ferna — APPROVED** [review]
